### ISSUE TITLE
Improve Site layout 

### ISSUE THREAD

**Issue by shiningshani** [mobtimeapp/mobtime-web#4]
I want to change the layout of site which will make it look good. Please assign this task to me.

**Comment by mrozbarry** [comment]
I'm open to discussing a layout change if you can show me.

**Comment by mrozbarry** [comment]
I am also already working towards a different layout that I've been working on, https://play.tailwindcss.com/C5Y4IjkeuZ

**Comment by mrozbarry** [comment]
@shiningshani presuming you're after a hacktoberfest badge of some sort, you're going to have to communicate with me a bit. Are you a designer? Do you use mobtime currently? What improvements do you want to make? Can you show me screenshots of anything of what your plan is?

**Comment by mrozbarry** [comment]
I'm going to close this issue. If you can work with me, I'm willing to discuss a layout/design change.
